
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: bdm-client-prod
    ports:
      - "3001:3001"   # Expose to host
    environment:
      - .env
    restart: unless-stopped
    networks:
      - bdm-network

networks:
  bdm-network:
    driver: bridge
